# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
    - package-ecosystem: 'npm' # See documentation for possible values
      directory: '/' # Location of package manifests
      schedule:
          interval: 'daily'
      cooldown:
          default-days: 3
      ignore:
          - dependency-name: 'react-native'
            update-types:
                ['version-update:semver-minor', 'version-update:semver-major']
          - dependency-name: 'react'
            update-types:
                ['version-update:semver-minor', 'version-update:semver-major']
          - dependency-name: '@types/react'
            update-types:
                ['version-update:semver-minor', 'version-update:semver-major']
          - dependency-name: '@react-native-community/slider'
            update-types:
                ['version-update:semver-minor', 'version-update:semver-major']
          - dependency-name: 'react-native-gesture-handler'
            update-types:
                ['version-update:semver-minor', 'version-update:semver-major']
          - dependency-name: 'react-native-maps'
            update-types:
                ['version-update:semver-minor', 'version-update:semver-major']
          - dependency-name: 'react-native-reanimated'
            update-types:
                ['version-update:semver-minor', 'version-update:semver-major']
          - dependency-name: 'react-native-screens'
            update-types:
                ['version-update:semver-minor', 'version-update:semver-major']
          - dependency-name: 'react-native-worklets'
            update-types:
                ['version-update:semver-minor', 'version-update:semver-major']
